### ISSUE TITLE
Como taxonomista, eu gostaria de validar uma lista de nomes espécies no site "The Plant List", de modo que eu possa saber quais são os nomes válidos das espécies e quais são as sinonímias de cada espécie. 

### ISSUE THREAD

**Issue by eliveltonFernando2016** [reginaldo-pro/taxonhub#3]
Link site: http://www.theplantlist.org/
- [x] #23 
- [x] #24 
- [x] #25 
- [x] #26 

[validar_especies_TPL.pdf](https://github.com/reginaldo-pro/taxonhub/files/6337909/validar_especies_TPL.pdf)

**Comment by LuizHenriqueBO** [comment]
- [ ]  Procurar componente para upload de arquivo no React
- [ ] Conexão com o site "Flora do Brasil"
- [ ]  Criar lista de nomes de espécies
- [ ] Validar lista de nome de espécies
- [ ] Normalizar dados obtidos
- [ ] Gerar CSV de dados normalizados
