### ISSUE TITLE
Como taxonomista, gostaria de validar uma lista de nomes de espécies no site "Flora do Brasil", de modo que eu possa saber quais são os nomes válidos das espécies e quais são as sinonímias de cada espécie.

### ISSUE THREAD

**Issue by eliveltonFernando2016** [reginaldo-pro/taxonhub#4]
Site: http://floradobrasil.jbrj.gov.br/reflora/PrincipalUC/PrincipalUC.do

O site possui uma api para obtenção dos dados.

**Comment by AnaFrozza** [comment]
- [ ] Conexão com o site "Flora do Brasil"
- [ ] Criar lista de nomes de espécies
- [ ] Validar lista de nome de espécies
- [ ] Normalizar dados obtidos
