### ISSUE TITLE
Implementação SpeciesLinkValidator

### ISSUE THREAD

**Issue by Jmallone** [reginaldo-pro/taxonhub#7]
- [x] Implementar a função `validateSpecies(json)`
- [x]  Implementar casos de teste

**Comment by JulianoCP** [comment]
A função validateSpecies(json) 
-Deve:
- [x] Fazer a verificação da coluna longitude.
- [x] Fazer a verificação da coluna latitude.
- [x] Fazer a análise da coluna E --> retirada dos nomes que não são binomiais.
- [x] Fazer a retirada de registros sem informação de coordenadas nas colunas AH, AI, AJ e AK.
- [x] Fazer a retirada dos registro AH, AI com informação bloqueada.
- [x] Fazer a retirada de registros com a informação "boqueada" nas colunas AH e AI.
- [x] Deve gerar um json com as ocorrências validas que foram obtidas pela API.

Teste para validateSpecies(json) 
Casos de teste:
- [x] Teste para a função verifyLatitudeLongitudeMun().
- [x] Teste para a função verifyNameBinomiais().
- [x] Teste para a função verifyLatitudeLongitude().
- [x] Teste para função principal validateSpecies().

A função validateSpecies(json) 
-Retornos da função:
##Quando valido:
- [x] Retorna um vetor de 2 posições:
    - [x] A primeira posição com as ocorrências em formato json validas.
    - [x] A segunda posição com as ocorrências em formato json invalidas.

##Quando não for valido:
- [x] Retorna null.
